support unicode character
  File "C:\Python27\lib\site-packages\gspread_dataframe.py", line 86, in _cellrepr
    value = str(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

Hi, i am using the set_with_dataframe() while having some cells with Chinese characters, and i encounter the error above. I don't know it just doesn't support the unicode or is me using it wrongly. 
then i change the str() to encode('utf-8'), the error is gone. if it won't bring other bugs, maybe you should change it.